spring:
  thymeleaf:
    encoding: UTF-8
    check-template: true
    prefix: classpath:/templates/
    mode: html
    suffix: .html
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8081
