spring:
  config.activate.on-profile: local
  h2.console:
    enabled: true
    path: /h2-console

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test-db
      driver-class-name: org.h2.Driver
      username: sa
      password:
      connection-test-query: SELECT 1
